// Package bench provides reusable benchmarking helpers for RKNN example
// applications and other performance-sensitive code.
//
// The package supports:
//
//   - Warmup iterations
//   - Timed benchmark iterations
//   - Collection of named timing metrics
//   - Automatic total execution timing
//   - Percentile statistics (p50, p90, etc.)
//   - Min/max timing statistics
//
// The benchmark runner is intentionally generic and uses a closure-based
// callback model so that callers can benchmark arbitrary code paths while
// reporting custom timing phases such as:
//
//   - inference
//   - postprocess
//   - rendering
//   - preprocessing
//
// Example:
//
//	report, err := bench.Run(bench.Config{
//		Warmup: 5,
//		Count:  100,
//		Metrics: []string{
//			"inference",
//			"postprocess",
//			"render",
//		},
//	}, func() (map[string]time.Duration, error) {
//		start := time.Now()
//
//		// inference...
//		endInference := time.Now()
//
//		// postprocess...
//		endPost := time.Now()
//
//		// rendering...
//		endRender := time.Now()
//
//		return map[string]time.Duration{
//			"inference":   endInference.Sub(start),
//			"postprocess": endPost.Sub(endInference),
//			"render":      endRender.Sub(endPost),
//		}, nil
//	})
//
//	if err != nil {
//		log.Fatal(err)
//	}
//
//	report.Print()
package bench

import (
	"log"
	"sort"
	"time"
)

// Func defines the benchmark callback function.
//
// The callback is executed once per benchmark iteration and should return
// a map of named timing metrics.
//
// The benchmark package automatically measures the total execution time
// of the callback and stores it under the "total" metric.
//
// Example returned metrics:
//
//	return map[string]time.Duration{
//		"inference":   inferenceTime,
//		"postprocess": postProcessTime,
//		"render":      renderTime,
//	}, nil
type Func func() (map[string]time.Duration, error)

// Config defines benchmark execution settings.
type Config struct {

	// Count is the number of timed benchmark iterations to execute.
	//
	// If Count is less than or equal to zero, a default value of 100
	// iterations will be used.
	Count int

	// Warmup is the number of untimed warmup iterations to execute before
	// benchmark timing begins.
	//
	// Warmup runs are useful for:
	//
	//   - CPU frequency scaling stabilization
	//   - cache warming
	//   - allocator initialization
	//   - RKNN/NPU runtime warmup
	Warmup int

	// Metrics defines the ordered list of metric names expected from
	// the benchmark callback.
	//
	// Example:
	//
	//	[]string{
	//		"inference",
	//		"postprocess",
	//		"render",
	//	}
	Metrics []string
}

// Report contains all collected benchmark timing samples.
type Report struct {

	// Count is the number of timed benchmark iterations executed.
	Count int

	// Warmup is the number of warmup iterations executed.
	Warmup int

	// Metrics contains the ordered list of benchmark metric names.
	Metrics []string

	// Samples contains all timing samples grouped by metric name.
	//
	// The "total" metric is automatically generated by the benchmark
	// runner and contains the total execution time of the callback.
	Samples map[string][]time.Duration
}

// Stats contains sorted timing values used for percentile and min/max
// calculations.
type Stats struct {

	// Values contains sorted timing samples in ascending order.
	Values []time.Duration
}

// Run executes a benchmark using the supplied configuration and callback.
//
// The supplied callback function is executed:
//
//	totalRuns = Warmup + Count
//
// times. Warmup runs are discarded from the final statistics.
//
// The benchmark package automatically measures total callback execution
// time and stores it under the "total" metric.
//
// The callback is responsible for measuring and returning any additional
// timing phases.
//
// Example:
//
//	report, err := bench.Run(cfg, func() (map[string]time.Duration, error) {
//		...
//	})
func Run(cfg Config, fn Func) (Report, error) {

	// Default benchmark iteration count.
	if cfg.Count <= 0 {
		cfg.Count = 100
	}

	totalRuns := cfg.Warmup + cfg.Count

	report := Report{
		Count:   cfg.Count,
		Warmup:  cfg.Warmup,
		Metrics: append([]string{}, cfg.Metrics...),
		Samples: make(map[string][]time.Duration),
	}

	// Allocate timing storage for each metric.
	for _, name := range report.Metrics {
		report.Samples[name] = make([]time.Duration, 0, cfg.Count)
	}

	// Allocate timing storage for automatic total execution timing.
	report.Samples["total"] = make([]time.Duration, 0, cfg.Count)

	for i := 0; i < totalRuns; i++ {

		// Start total iteration timer.
		start := time.Now()

		// Execute benchmark callback.
		values, err := fn()
		if err != nil {
			return report, err
		}

		// Measure total callback execution time.
		total := time.Since(start)

		// Skip warmup iterations.
		if i < cfg.Warmup {
			continue
		}

		// Store named metric timings.
		for _, name := range report.Metrics {
			report.Samples[name] = append(report.Samples[name], values[name])
		}

		// Store total iteration timing.
		report.Samples["total"] = append(report.Samples["total"], total)
	}

	return report, nil
}

// NewStats creates a Stats instance from timing values.
//
// The values are copied and sorted in ascending order so percentile,
// minimum, and maximum operations can be performed efficiently.
func NewStats(values []time.Duration) Stats {

	// Copy values so caller slice ordering is not modified.
	copied := append([]time.Duration{}, values...)

	// Sort timing values in ascending order.
	sort.Slice(copied, func(i int, j int) bool {
		return copied[i] < copied[j]
	})

	return Stats{Values: copied}
}

// Min returns the minimum timing value.
//
// Returns zero if no values exist.
func (s Stats) Min() time.Duration {
	if len(s.Values) == 0 {
		return 0
	}

	return s.Values[0]
}

// Max returns the maximum timing value.
//
// Returns zero if no values exist.
func (s Stats) Max() time.Duration {
	if len(s.Values) == 0 {
		return 0
	}

	return s.Values[len(s.Values)-1]
}

// Percentile returns the requested percentile timing value.
//
// The percentile must be specified as a floating-point value in the range:
//
//	0.0 to 1.0
//
// Example:
//
//	p50 := stats.Percentile(0.50)
//	p90 := stats.Percentile(0.90)
//
// Returns zero if no values exist.
func (s Stats) Percentile(p float64) time.Duration {
	if len(s.Values) == 0 {
		return 0
	}

	idx := int(float64(len(s.Values)-1) * p)

	return s.Values[idx]
}

// Print outputs benchmark statistics using the standard log package.
//
// Statistics are printed for:
//
//   - all configured metrics
//   - the automatically generated "total" metric
//
// Example output:
//
//	inference: min=6.2ms p50=6.5ms p90=6.8ms max=7.1ms
func (r Report) Print() {

	log.Printf("Benchmark count=%d warmup=%d",
		r.Count, r.Warmup,
	)

	// Print configured metrics first.
	names := append([]string{}, r.Metrics...)

	// Append automatically generated total timing metric.
	names = append(names, "total")

	for _, name := range names {

		stats := NewStats(r.Samples[name])

		log.Printf(
			"%s: min=%s p50=%s p90=%s max=%s",
			name,
			stats.Min(),
			stats.Percentile(0.50),
			stats.Percentile(0.90),
			stats.Max(),
		)
	}
}
